### ISSUE TITLE
Hello, can you help me? 

### ISSUE THREAD

**Issue by MelodyAustin** [upasnarayan/Chemical-Equation-Balancer#1]
Hello! I was going through github for some chemistry related codes for my brother, and found this one. And what an amazing app did you make! This is like the best app for any chemistry student out there! 
I have tried to open this up in android studio but there seems to more than one errors in android studio.
The if(final == null) code doesn't seem to work and I cant understand what is supposed to be there to make it work and rterms is not recognised too. 
Please can you tell me what must be done to get it working without the errors?

**Comment by upasnarayan** [comment]
Sorry for the errors. I had refactored the code, but didn't fully test it out before uploading to github (this is an app I published 5 years ago but just uploaded to github recently). I just pushed some fixes, so it should hopefully be working now. Let me know if it works for you now!
